# Build stage
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Runtime stage
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/servify/browser ./
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
